### ISSUE TITLE
Default save location for tokens not remembered

### ISSUE THREAD

**Issue by JamzTheMan** [JamzTheMan/MapTool#19]
When saving token and token images, file save dialog defaults to app directory and should default to last save location.  Also, changing save 'type" resets directory location.

**Comment by JamzTheMan** [comment]
Fixed so token saving now defaults to last file save location and saves the same. Also, changing "file filter types" no longer changes directory, only the default name.

**Comment by Sereptus** [comment]
I'm sorry James but I've downloaded the latest versions every update and I still continue to have this issue. Hate to be a pest but like I said, I have the latest version. 1.4.20 from here. Am I missing something? :?

**Comment by JamzTheMan** [comment]
It's fixed for next release, 1.4.4.0. I have a beta out but official release will come out soon...

**Comment by Sereptus** [comment]
Ooooh, ok. Thanks for all your hard work and dedication! I'm just setting up for Storm Kings Thunder (D&D 5E) so I'll hold off on doing the entire Monster Manual from 5E until the new release. I also find myself becoming very passionate about attempting to change the sight code to where a token that, for example, has Darkvision 30 ft to change the vision seen on screen as something like 22 feet of vision and then sort of a soft fog for the last 8 feet. Sorry if I'm unclear with that but I've been at work for 14 hours and am stubbornly staying awake. Anyway, I'd love to get a compile of Maptool so I could sort through the bits and pieces and screw around with it. Is this possible? Maybe your NERPS compile? I dunno, maybe I'll get some sleep and get back to ya. Thanks again.

**Comment by JamzTheMan** [comment]
Are you taking about changing within maptool or in the Java code?

And if you want, a beta is up, just go to releases on GitHub.

**Comment by JamzTheMan** [comment]
OK, so this is partially fixed. It's using the saved location for files (where you last saved campaign/exported maps, but when saving tokens, it's not updating/saving the new location...

**Comment by JamzTheMan** [comment]
Low hanging fruit... if someone wants to knock this one out...
